### ISSUE TITLE
In glutil/scripts/fxp_sync.sh double verify-certificate?

### ISSUE THREAD

**Issue by scriptzteam** [nixnodes/glutil#2]
https://github.com/nixnodes/glutil/blob/master/scripts/fxp_sync.sh

LFTP_SYNC_OPTS="set ssl:verify-certificate off;
set ssl:verify-certificate off;

two times defined the same?

**Comment by nixnodes** [comment]
Indeed. That thing, with the rest of fxp_*.sh scripts, is horribly broken and should not be used. 

Honestly, I was kinda suprised to see its still in there, it should have been removed from the master branch long ago.
